### ISSUE TITLE
Você tem o livro?

### ISSUE THREAD

**Issue by faustinopsy** [lpaulopds/PadroesDeProjetoPHP#1]
olá gostaria de saber se você ainda possui o livro e quer repassar-lo a bom preço?

**Comment by lpaulopds** [comment]
Comprei no formato digital pelo Play Livros, procurei agora pra consultar o preço e parece que ele não está disponível na plataforma do Google. Um outro bom livro sobre PHP é o: PHP Programando com Orientação a Objetos do Pablo Dall'Oglio, que também parece não está disponível. De qualquer maneira estou a disposição pra falar sobre PHP e desenvolvimento web no geral.

**Comment by faustinopsy** [comment]
valeu, encontrei em um sebo, a consulta do livro é para referenciar trabalhos para alunos.
